development:
	adapter: oracle_enhanced
	host:jackdb.cipsboubatuq.us-east-1.rds.amazonaws.com
	port:1521
	database:jackdb.cipsboubatuq.us-east-1.rds.amazonaws.com/TESTRDS
	username:jackchen
	password:cis5502015

